#!/bin/bash
#skripti algus
echo "sisesta kuu number: "
read kuu
if test $kuu -eq 12 -o $kuu -eq 1 -o $kuu -eq 2
then
echo "pragu on talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
echo "praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
echo "praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then
echo "praegu on sügis"
elif test $kuu -ge 13 -o $kuu  -le 0
then
echo "seda kuud ei ole kalendris, proovi uuesti"
fi

