#!/bin/bash
#skripti algus
kell=`date "+%H"`
user=`whoami`
if [ $kell -ge 6 -a $kell -lt 12 ]
then
echo "Tere hommikust," $user
elif [ $kell -ge 12 -a $kell -lt 18 ]
then
echo "Tere päevast," $user
elif [ $kell -ge 18 -a $kell -lt 22 ]
then
echo "Tere õhtust," $user
elif [  $kell -ge 22 -a $kell -lt 25 ] || [ $kell -ge 0 -a $kell -lt 6  ]
then
echo "Head ööd," $user
fi
