#!/bin/bash
#skripti algus
echo "mitu rida? "
read i
echo "mitu tärni reas? "
read j
for (( f = 1; f <= $i; f++ ))
	do
	echo -n $f". "
		for (( g = 1; g <= $j; g++ ))
		do
		echo -n "*"
	done
	echo ""
done
echo -n $i". "
echo ""
